name: Playwright Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Cache Playwright browsers
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: playwright-browsers-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            playwright-browsers-

      - name: Debug baseURL from secrets
        run: echo "baseURL is ${{ secrets.NEXT_PUBLIC_SERVER_URL }}"  # Console log the baseURL value

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Start the local dev server
        run: npm run dev &  # Start the server in the background

      - name: Wait for the server to be ready
        run: npx wait-on http://localhost:3000  # Wait until the app is ready

      - name: Run Playwright tests
        run: npx playwright test
